# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: default

steps:
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(System.DefaultWorkingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Azure subscription 1(c37c0729-6ee1-4911-9155-738994d132d9)'
    appType: 'webApp'
    appName: 'DevOpsWebAppA1'
    package: '$(System.DefaultWorkingDirectory)/*.zip'
    deploymentMethod: 'auto'

